//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.1-SNAPSHOT
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.1-SNAPSHOT")]
public interface IExprListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult([NotNull] ExprParser.MultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Mult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult([NotNull] ExprParser.MultContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Minus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinus([NotNull] ExprParser.MinusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Minus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinus([NotNull] ExprParser.MinusContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] ExprParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] ExprParser.RootContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] ExprParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] ExprParser.AddContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSub([NotNull] ExprParser.SubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Sub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSub([NotNull] ExprParser.SubContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] ExprParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] ExprParser.IntContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Paren"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParen([NotNull] ExprParser.ParenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Paren"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParen([NotNull] ExprParser.ParenContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.Div"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiv([NotNull] ExprParser.DivContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.Div"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiv([NotNull] ExprParser.DivContext context);
}
